---
- name: "Ensure Canonical's livepatch is present"
  command: "/usr/bin/snap install canonical-livepatch"
  ignore_errors: true
  become: true

- name: Check livepatch status
  command: "/snap/bin/canonical-livepatch status --verbose"
  changed_when: false
  register: livepatch
  ignore_errors: true
  become: true

- debug: msg="WARNING! Possible error in current livepatch configuration. Please check."
  when: livepatch is defined and livepatch.stdout is defined and livepatch.stdout.find("checkState{{ ':' }} check-failed") != -1

- name: Ubuntu xenial | Enable livepatch
  command: "/snap/bin/canonical-livepatch enable {{ livepatch_token }}"
  no_log: true
  when: livepatch_token != "" and livepatch is defined and livepatch.stdout is defined and livepatch.stdout.find("Machine is not enabled.") != -1
  become: true
